### ISSUE TITLE
recursive makefile or not?

### ISSUE THREAD

**Issue by ickc** [pandoc/lua-filters#1]
Probably I should migrate <https://github.com/pandoc-extras/luapandoc-filters> to this one. Currently, the makefile I setup in pandoc-extras/luapandoc-filters is a plain makefile (that does not use recursion). But the makefile in pandoc/lua-filters by @jgm uses recursive makefile.

Recursive makefile will

- allows more flexibility for each individual filters

while a "plain" makefile will

- have less work for each pull request, that they may not know how to write a makefile
- can still has a tailored rule for special filters if the default rule doesn't cut

I planned to setup a Travis CI to auto-check this, and requires pull requests should have a corresponding example for both a test and as an example. This example will not only be used as a test in CI, but also as a rendered example in an automated "gallery" for filters.

**Comment by jgm** [comment]
My reasoning was that, with recursive Makefiles, every
filter can be fitted with its own example and test suite.

There are other possible approaches, e.g. each filter could
come with a shell script that runs the tests.  But a
Makefile is very flexible.

Anyway, I'm open to other suggestions here; this was just
meant as one possible framework.

**Comment by ickc** [comment]
What do you think about using single makefile with optional custom rule overriding a general pattern rule?

**Comment by jgm** [comment]
+++ Kolen Cheung [Dec 12 17 04:57 ]:
>   What do you think about using single makefile with optional custom rule
>   overriding a general pattern rule?

Not sure what you mean, maybe you could give an example?

**Comment by ickc** [comment]
The makefile I wrote previously is in <https://github.com/pandoc-extras/luapandoc-filters/blob/master/makefile>.

The idea is to have one single makefile and convention for organizing stuffs (including test, example, etc.), but whenever a filter calls for deviation from this convention, an overriding rule can be created below it.

**Comment by ickc** [comment]
Seems like it has been settled.
