### ISSUE TITLE
Feature request: Relative file import in include-files filter

### ISSUE THREAD

**Issue by gabyx** [pandoc/lua-filters#102]
Would it make sense to add an attribute `relative-to-current-dir=true` or something such that, all paths or better all relative paths are resolved to the current file path we are currently at (maybe not so easy to distinguish platform independent, relative vs absolute paths). 
Therefore maybe, just replace a variable "${current-dir}/b/c.md" in all paths, which would give a deterministic and consistent way of relative imports :)? 

@tarleb: What do you think?

In `a/b.md`
<pre>
``` { .include}
${current-dir}/b/c.md
```
</pre>

or 
In `a/b.md`
<pre>
``` { .include relative-to-current-dir=true}
./b/c.md
```
</pre>

**Comment by tarleb** [comment]
This is a good idea, but poses some problems. Lua, by default does not include the tools to deal with path modifications. Paths are platform dependent, with path separators `\` on Windows and `/` on Linux and Mac. There are two possibilities to support path modifying functions such as `dirname` or `is_relative`:

1. Write a pure Lua implementation, or
2. expose the path handling library used by pandoc.

Neither is especially difficult, but both options require more work than I'm willing/able to invest right now.

Patches would be most welcome.

**Comment by gabyx** [comment]
I can certainly do a PR. What do you mean with pure Lua? Isn’t there a std lib for path modifications? The path handling library by pandoc is haskell, right? With a python filter this would be really easy to acomplish, but I dont know about the `walk_****` functions...

**Comment by tarleb** [comment]
Great!

Lua aims to run on any platform that can be targeted with ANSI C. The latter has no concept of paths, so neither has Lua. Path libraries for Lua exist, but are all written in C, and thereby not an option. The necessary path manipulations should still be doable by pure string manipulations.

The path library used in pandoc is [filepath](https://hackage.haskell.org/package/filepath). If you are interested in how this can be exposed to Lua, check [hslua-module-system](https://hackage.haskell.org/package/hslua-module-system), which exposes selected system and file related function. Exposing filepath would best be done by adding the necessary bindings to that package.

**Comment by gabyx** [comment]
Probably these functions are the only ones which give enough access to do almost if not all path handling issues in filters:

- [takeDirectories](https://hackage.haskell.org/package/filepath-1.4.2.1/docs/System-FilePath-Posix.html#v:takeDirectory)
- [takeFileName](https://hackage.haskell.org/package/filepath-1.4.2.1/docs/System-FilePath-Posix.html#v:takeFileName)
- [splitDirectories](https://hackage.haskell.org/package/filepath-1.4.2.1/docs/System-FilePath-Posix.html#v:splitDirectories)
- [takeExtensions](https://hackage.haskell.org/package/filepath-1.4.2.1/docs/System-FilePath-Posix.html#v:takeExtensions)
- [combine](https://hackage.haskell.org/package/filepath-1.4.2.1/docs/System-FilePath-Posix.html#v:combine)
- [isRealative](https://hackage.haskell.org/package/filepath-1.4.2.1/docs/System-FilePath-Posix.html#v:isRelative)
- [normalise](https://hackage.haskell.org/package/filepath-1.4.2.1/docs/System-FilePath-Posix.html#v:normalise)

Any help and review is kindly welcome.
I will try next week what I can do, I think I can directly build and test the [hslua](https://hackage.haskell.org/package/hslua-module-system) module.

**Comment by gabyx** [comment]
What would be the next step to test a merged PR: https://github.com/hslua/hslua-module-system/pull/1
with this include-filter. How to we get these changes here?

**Comment by gabyx** [comment]
Got it: :-) See https://github.com/jgm/pandoc/pull/6565

**Comment by lmunch** [comment]
@gabyx I think latest changes to include-files will solve this issue. Please check.

**Comment by gabyx** [comment]
@lmunch  Thats really greate to hear: Is the doc already up to date, because I ve not seen any explanation on the feature?

**Comment by lmunch** [comment]
@gabyx See the Recursive transclusion sections. It's default behaviour now, so no feature flag.

**Comment by gabyx** [comment]
@lmunch : Thanks for the effort! Its great! Sorry I was to impatient to read carefully!

**Comment by lmunch** [comment]
Resolved with #173
