### ISSUE TITLE
Lua filters deserve BETTER MARKETING.

### ISSUE THREAD

**Issue by stroobandt** [pandoc/lua-filters#121]
Lua filters deserve **BETTER MARKETING.**
Currently. Lua filters look more like [an afterthought at the bottom of the Extras page](https://pandoc.org/extras.html).
When one eventually lands on [this `README.md`](https://github.com/pandoc/lua-filters/), it becomes a _GitHub dumpster dive_ to find out which Lua filter does what. I would suggest adding one paragraph descriptions to the general [`README.md`](https://github.com/pandoc/lua-filters/) and do something similar on the [Extras page](https://pandoc.org/extras.html).

Feel free to discuss this here.

**Comment by a-vrma** [comment]
> When one eventually lands on [this `README.md`](https://github.com/pandoc/lua-filters/), it becomes a _GitHub dumpster dive_ to find out which Lua filter does what. I would suggest adding one paragraph descriptions to the general [`README.md`](https://github.com/pandoc/lua-filters/) and do something similar on the [Extras page](https://pandoc.org/extras.html).

Agree with the first part. We could write a script that merges all the READMEs
and appends them to the root README. Maybe we could use `include-files.lua`?

**Comment by tarleb** [comment]
See [branch html-pages](https://github.com/tarleb/lua-filters/tree/html-pages) for my plans to improve on the current situation. I'd like to have a separate website, with a separate page for each filter, and an overview page featuring the paragraph between the main heading and first second-level heading. Example filter page:
[pagebreak.zip](https://github.com/pandoc/lua-filters/files/5397431/pagebreak.zip)

**Comment by tarleb** [comment]
We've created a new org [pandoc-ext](https://github.com/pandoc-ext) to make filters more visible. New filters are announced on [Mastodon](https://fosstodon.org/@pandoc). Quarto-related pages like [awesome-quarto](https://github.com/mcanouil/awesome-quarto) mention the filters, too.

While we could still do more, it's enough for me to consider this done.

**Comment by stroobandt** [comment]
@tarleb Great! But what needs to be done for my [math2svg Lua filter](https://github.com/pandoc/lua-filters/tree/master/math2svg) to make it onto the list?

**Comment by alerque** [comment]
@tarleb I know my attention has been devoured in other directions lately, but I do come round to Pandoc & especially Lua stuff now and then. If you want triage/maintenance/ci help on the new org feel free to invite and I'll pitch is as time permits.

**Comment by tarleb** [comment]
> @tarleb Great! But what needs to be done for my [math2svg Lua filter](https://github.com/pandoc/lua-filters/tree/master/math2svg) to make it onto the list?

The filter migration is work in progress, I didn't get to math2svg yet. I generally encourage contributors to maintain filters under their own namespace and to mention them in [pandoc-ext/info](https://github.com/pandoc-ext/info) (e.g., https://github.com/b3/include-code-files), but I'm also happy to move the code to a repo in pandoc-ext and give the maintainer access (as happened with list-table). Just let me know your preference.

**Comment by tarleb** [comment]
> If you want triage/maintenance/ci help on the new org feel free to invite and I'll pitch is as time permits.

Thanks, I'll gladly take you up on that.

**Comment by stroobandt** [comment]
> move the code to a repo in pandoc-ext and give the maintainer access

I prefer the above option for `math2svg`. Thanks!

**Comment by tarleb** [comment]
I've created the repo and given you access. It's set to "private" for now, because I aim for all repos in the pandoc-ext org to follow a few common patterns, which we'll have to add to math2svg first. I've yet to write those patterns down in detail, but the gist is:

- [x] Good docs
- [x] MIT license
- [ ] Usable as a Quarto extension (if the filter makes sense in that context)
- [ ] Options should be taken from an object with the same name as the filter, e.g.,
  ``` lua
  my-filter:
    setting1: true
    setting2: [this, that]
    # etc.
  ```

I plan to publish another filter that will create this structure from `myfilter_foo` and `myfilter.bar` values, so old math2svg configs will still be usable.

**Comment by bpj** [comment]
Den lör 29 apr. 2023 21:12Albert Krewinkel ***@***.***> skrev:

> If you want triage/maintenance/ci help on the new org feel free to invite
> and I'll pitch is as time permits.
>
> Thanks, I'll gladly take you up on that.
>
I might be able to lend a hand as well as and when I have time.
