### ISSUE TITLE
scholarly-metadata produces error: "~/.local/share/pandoc/filters/scholarly-metadata.lua:95: not a named object: table: 0x62cafe0"

### ISSUE THREAD

**Issue by kaarelmand** [pandoc/lua-filters#142]
Pandoc fails when trying to run the scholarly-metadata lua filter on a minimal example:
```
> cat test.md

---

title: "test title"
institute:
  - tst: "test institute"
author: 
  - John Doe:
    institute: [tst]
...

test
```

I get this traceback:
```
> pandoc -o test.pdf --lua-filter=scholarly-metadata.lua test.md 

Error running filter ~/.local/share/pandoc/filters/scholarly-metadata.lua:
...~/.local/share/pandoc/filters/scholarly-metadata.lua:95: not a named object: table: 0x6781a80
stack traceback:
	[C]: in function 'error'
	...~/.local/share/pandoc/filters/scholarly-metadata.lua:95: in function 'to_named_object'
	[string "--[[..."]:119: in function 'pandoc.List.map'
	...~/.local/share/pandoc/filters/scholarly-metadata.lua:145: in upvalue 'canonicalize'
	...~/.local/share/pandoc/filters/scholarly-metadata.lua:181: in function <...~/.local/share/pandoc/filters/scholarly-metadata.lua:180>
```
My Pandoc version is 2.11 (from conda-forge), running on Ubuntu 20.04.

**Comment by tarleb** [comment]
I think `institute: [tst]` should be indented by two more spaces.

**Comment by kaarelmand** [comment]
Oh wow, thanks! That fixed the error; embarrassing mistake on my part.

However, though pandoc runs successfully now, this is what the output looks like (instead of 'John Doe' I get 'test'):

![](https://user-images.githubusercontent.com/16322491/99261622-a1e56b00-2825-11eb-8f9f-5e6957cf8b0c.png)

 Anything else I might be doing wrong?

**Comment by kaarelmand** [comment]
Hmm, nevermind, figure out I need to use the `author-info-block` lua filter as well. I wonder if this should be in the readme file...

**Comment by tarleb** [comment]
Good idea! Added in 67adc5bc516975d9e66e391bbd4e383aa657e8f4.
