### ISSUE TITLE
Enabling the wiki as a place to share lua filter tips

### ISSUE THREAD

**Issue by bpj** [pandoc/lua-filters#156]
What about enabling the wiki for this repository as a place where people can share functions, idioms, tips and solutions which are useful in Lua filters?

I have a bunch of such things collected since Lua filters were introduced. An alternative might be to write and maintain a library of helper functions but that seems a little like overkill and might actually make things more complicated than they need to be, not least because people would need to install such a library into their Lua path, which even may mean that they need to set their `LUA_PATH` and/or `LUA_PATH_<version>` variables which they might not need otherwise.

I'm thinking a setup with one page per tip or group of related tips for easy navigation.

**Comment by jgm** [comment]
Good idea. I think it's enabled now, so go ahead!

**Comment by bpj** [comment]
@jgm It is accessible but you have to set it so that anyone can edit and/or add pages.

**Comment by jgm** [comment]
OK, I think I did that just now, can you try again?

**Comment by bpj** [comment]
@jgm it works now. Thanks!
