### ISSUE TITLE
multiple-bibliographies: problem with numeric csl for pdf output

### ISSUE THREAD

**Issue by gnpan** [pandoc/lua-filters#158]
pandoc 2.11.4

If a numeric format csl (e.g. [ieee.csl](https://www.zotero.org/styles?q=ieee&format=numeric)) is used to create a pdf, a latex error occurs:
```
Error producing PDF.
! Undefined control sequence.
l.65 \CSLLeftMargin
```
There is no problem with .docx output. To reproduce with provided sample files: 
```
 pandoc --citeproc --csl=ieee.csl --lua-filter=multiple-bibliographies.lua -o sample.pdf sample.md
```

**Comment by tarleb** [comment]
Not sure yet why this happens, but you can work around it by calling pandoc with `-V csl-refs`.

**Comment by gnpan** [comment]
Thanks, it works fine with -V csl-refs.
