### ISSUE TITLE
multiple-bibliographies with numeric format csl and html output

### ISSUE THREAD

**Issue by gnpan** [pandoc/lua-filters#165]
When using a numeric format csl, e.g. [ieee](https://www.zotero.org/styles?q=ieee) and the following pandoc command for html output:

`pandoc -s --citeproc --csl=ieee.csl --lua-filter=multiple_bibliographies.lua -o sample.html sample.md`

the formated citations appear under the numbers, like this:
[1]
F. Nietzsche, Die geburt der tragödie aus dem geiste der musik. 1872.
[2]
Bellori, Le vite de’ pittori, scultori e architetti moderni. 1672.

instead of 
[1]    F. Nietzsche, Die geburt der tragödie aus dem geiste der musik. 1872.
[2]    Bellori, Le vite de’ pittori, scultori e architetti moderni. 1672.

which you get without the lua filter (just one bibliography and ::: {#refs}).
Same problem with any other numeric format csl.

**Comment by jdutant** [comment]
Hi there, I don't get that bug. But if you do, I suspect it is a CSS issue: the output code of bibliography entries is the same whether you use the filter or not, all that's needed is that the document's CSS (which by default pandoc puts in the header of the html output in a <style> class) includes:

```
   div.csl-left-margin {
      min-width:2em;
      float:left;
    }
 ```

Here is the test I've run. Versions:

```
pandoc 2.11.4
Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2,
citeproc 0.3.0.5, ipynb 0.1.0.1
```

**sample_simple.md**
```markdown
---
title: Simple Bibliographies Demo
bibliography:
  - primary.bib
  - secondary.bib
nocite: '@Knu86, @Bae'
---
@Nie72, @Bel

# References
```

**sample_multiple.md**
```markdown
---
title: Multiple Bibliographies Demo
bibliography_sources: primary.bib
bibliography_recommended_reading: secondary.bib
nocite: '@Knu86, @Bae'
---
@Nie72, @Bel

# References

::: {#refs_sources}
:::

# Recommended Reading

::: {#refs_recommended_reading}
:::

```

Running:
```
pandoc --citeproc -s --csl ieee.csl sample_simple.md -o simple.html
pandoc -s --csl ieee.csl -L multiple-bibliographies.lua sample_multiple.md -o multiple.html
```

Output **simple.html**:
```html
<style>
...
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
 ...
</style>
...
<div id="ref-Bae" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">[3] </div><div class="csl-right-inline">O. Bätschmann, <em>Pygmalion als betrachter</em>. 1985.</div>
</div>
<div id="ref-Knu86" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">[4] </div><div class="csl-right-inline">D. E. Knuth, <em>The TeXbook</em>. 1986.</div>
```

Output **multiple.html**:
```html
<style>
...
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
...
</style>
...
<div id="ref-Knu86" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">[1] </div><div class="csl-right-inline">D. E. Knuth, <em>The TeXbook</em>. 1986.</div>
</div>
<div id="ref-Bae" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">[2] </div><div class="csl-right-inline">O. Bätschmann, <em>Pygmalion als betrachter</em>. 1985.</div>
</div>
...
```

**Comment by jdutant** [comment]
PS, I get the same output if I add `--citeproc` to the command processing `sample_multiple.md`.

Albert: should we add to the README.md whether and where to put --citeproc? It seems to me that:

* if you don't put `--citeproc`, the filter calls it on the bibliography anyway.
* if you put `--citeproc` before the filter, all is fine but you may get mistaken "citation not found warnings" (when the citation's source is in a `bibliography_TOPIC` file)
* if you put `--citeproc` after the filter, many/all citations are broken because they are replaced by `key?` when the citation's source is in a  `bibliography_TOPIC` file.

If that's right the README.md should perhaps advise to use the filter *instead of* --citeproc. 

I don't think you should put `--citeproc` in the command

**Comment by gnpan** [comment]
Thanks for the CSS advice. I have added the div.csl-left-margin... to a custom css and it works fine. Leaving --citeproc out didn't make a difference in my case. I confirm that having --citeproc together with the filter gives "citation not found" warnings, although the output is the same. So, there is no need to use it.

**Comment by jdutant** [comment]
If you're using a custom CSS you may want to add all of pandoc's csl-related CSS styling (use `pandoc -D html > template.html` to inspect pandoc's default template): 

```css
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
    }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
```

**Comment by gnpan** [comment]
Thanks, that looks good now with refs that are more than one line. I was halfway there by adding a  div.csl-right-inline, but this is the full works. Now, the strange thing is that although I have the latest pandoc version like you, the default html template does not seem to contain any CSS, which I guess explains why I was getting the problem running the command without the custom css (regardless of --citeproc) and you didn't. Maybe you have the template mentioned in [#6601:](https://github.com/jgm/pandoc/pull/6601/files)?

**Comment by jdutant** [comment]
If you run `pandoc -D html` you'll see your pandoc templates. It should call `styles.html()` to generate the CSS (in addition to calling any css you specify manually:

```html
  <style>
    $styles.html()$
  </style>
$for(css)$
  <link rel="stylesheet" href="$css$" />
$endfor$
```

If it does, and you still don't get a CSS in your output, I'm puzzled. As far as I can see these files are not stored anywhere in the system but included in the pandoc executable, so they should work fine if pandoc works.

**Comment by gnpan** [comment]
It's strange - when I run the above examples, in the single.html output the csl styling is all there just before </style>, but it is not there in the case of the multiple.html output. The rest of the style content is identical. So the default template is obviously the right one, but somehow the lua filter strips out the csl styling. Anyway, problem solved by using the custom css. Many thanks for your help.

**Comment by jdutant** [comment]
For me it's there with both.
