### ISSUE TITLE
Minimal working example of Lilypond lua filter with markdown 

### ISSUE THREAD

**Issue by dalbandea** [pandoc/lua-filters#167]
Hi, I'm trying to use the [lilypond](https://github.com/pandoc/lua-filters/blob/master/lilypond/lilypond.lua) filter to try to convert lilypond code inside a `.md` file into embedded images.

I'm tryind to test it with a simple example, but I cannot make it to work. I downloaded `lilypond.lua` into my working directory and this is my file `test.md`
```markdown
# Markdown file

Hi

\version "2.20.0"
{
  c' e' g' e'
}
```

And I call pandoc using `pandoc --lua-filter=lilypond.lua test.md -o test.pdf`. The error mesage is
```sh
Error producing PDF.
! Undefined control sequence.
l.60 \version
```

I also tried removing the `\version` line. Then it compiles and generated a pdf, but without image. My pandoc version is `2.11.4`, and mi lilypond version si `2.20.0`, running on Ubuntu 20.04.

Sorry if the question is stupid (I'm a newbie on both pandoc and lilypond), but I read lilypond's filter `README.md` and I cannot figure it out. Could you provide a minimal working example?

**Comment by tarleb** [comment]
The lilypond directory has two sample files used for testing, `oboe.md` and `appoggiaturas.md`. The exact test command can be found in `Makefile`, but I agree that this should be made easier to find.

**Comment by dalbandea** [comment]
Thank you! Now that you say it, it was deducible, but probably a line in the readme briefly mentioning that those files are examples that can be compiled with `make` would be nice for the next newbie coming here. :)

**Comment by alerque** [comment]
Lets keep this issue open until the documentation is fixed.

**Comment by ratnanil** [comment]
I'm not sure what I'm missing. But following the advice from PR #249 I run: 

```
pandoc --to=html --lua-filter=lilypond.lua --output="test.html" appoggiaturas.md 
```

whereas I get the following error message:

```
Error running filter lilypond.lua:
PandocIOError "pipe" lilypond: createProcess: posix_spawnp: does not exist (No such file or directory)
stack traceback:
        lilypond.lua:49: in upvalue 'generate_image'
        lilypond.lua:83: in upvalue 'process_lilypond'
        lilypond.lua:143: in function <lilypond.lua:138>
```

**Comment by tarleb** [comment]
Looks like pandoc cannot find the `lilypond` binary; it has to be installed separately.

**Comment by ratnanil** [comment]
> The `lilypond` executable must be installed to a location on your `PATH`

Oh sorry, completely missed that one :sleepy:

**Comment by tarleb** [comment]
You are right though: the error message *is* rather cryptic and should probably be improved.
