### ISSUE TITLE
bibexport executable

### ISSUE THREAD

**Issue by tolot27** [pandoc/lua-filters#17]
The prerequisites mention a `bibexport` excecutable. Please create a hyperlink to this tool. I've tried it with [bibexport.sh](https://github.com/highlando/latex-miscs/blob/master/bibexport.sh) and also with [bibtool](https://github.com/ge-ne/bibtool). None of them produced a valid bib file.

**Comment by tarleb** [comment]
It's the [bibexport](https://www.ctan.org/pkg/bibexport) tool by Nicolas Markey. It ships on Debian/Ubuntu in the texlive-bibtex-extra package. This should indeed be included in the readme.

I realized that the script isn't very complex – we might be able to replicate the relevant parts directly in lua.

**Comment by tolot27** [comment]
The [bibexport](https://www.ctan.org/pkg/bibexport) package does not run on Windows. I was only successful with `biber file --output_format bibtex` were `file` is the name of the latex file without its extension. But this only works with `\usepackage[backend=biber]{biblatex}`.

**Comment by tarleb** [comment]
I see. Maybe we should use a metadata field to allow chosing between bibexport and biber.
