### ISSUE TITLE
include-files and image paths

### ISSUE THREAD

**Issue by lmunch** [pandoc/lua-filters#171]
Hi

I have a main.md document which includes subdoc.md from a sub folder like so:
```

├── main.md
└── subdoc
    ├── image.svg
    └── subdoc.md

```
in subdoc.md I have `![title](image.svg)` but image.svg cannot be found. Instead I have to do `![title](subdoc/image.svg)` in order to get main.md to find the image, but then I cannot generate subdoc.md by itself without changing the image path again.

Should the image path not be updated by include-files if the image path is relative?

Thanks
Lars

**Comment by tarleb** [comment]
Yes, this would be a good idea. We have added a new `pandoc.path` module to Lua which should make it possible to implement this in a platform-independent way.

Help welcome!

**Comment by lmunch** [comment]
I have tried to implement the feature. Please bare with me, I have never done any Lua before nor Pandoc filters. The implementation only update image paths correctly in "first level" includes (recursion not yet correctly handled). Am I on the right track?

https://github.com/pandoc/lua-filters/commit/fe480492138a4dd7e1e9eb36a3fd3cfdedf42b7f

Thanks

**Comment by lmunch** [comment]
If you nest the include more than one level and use different directories then you have the same problem finding the markdown files as finding the images files, so the updated implementation instead set the working directory to that of the include file, so the recursion will work for relative path if not everything is in the same directory. If the image path is releative the the working path is prepended to the image path so the image can be located in the final document generation.

Please review https://github.com/lmunch/lua-filters/commit/7847ae5117f07ecf2f19721d4bd649378b4443c8#diff-af7df85768df2036ad319f384a57cc4d88ae4549d59804ce96d0b3cb4c8333e1

**Comment by lmunch** [comment]
Fixed by pull request https://github.com/pandoc/lua-filters/pull/172
