### ISSUE TITLE
pandoc-quotes, nested quotes in latex output

### ISSUE THREAD

**Issue by peripatetikos** [pandoc/lua-filters#179]
If I have an org-mode file with a line like `"This is a 'test'"` pandoc with pandoc-quotes and `-M lang=de` translates that into „This is a ‚test``` in a LaTeX file.  (Note the three acutes at the end.) So opening quotes are translated into German typographical quotes, but closing quotes into LaTeX code for a single closing quote (first acute) and then for a closing quote (two acutes). LaTeX get's mixed up and translates it into `„This is a ‚test“‘`. But the result should be „This is a ‚test‘“.

Given that the entry for `de` in `pandoc-quotes.lua` indicates the correct typographic form for opening _and_ closing quotes I'm wondering why they are not used for the closing quotes in the case of LaTeX. Would it be possible to change that?

I use pandoc 2.5 from ubuntu 20.04. My command line is:

`pandoc --lua-filter=pandoc-quotes.lua -M lang=de -s -f org -t latex test.org -o test.tex`

test.org is:

```
#+LANGUAGE: de
#+OPTIONS: ':t
#+OPTIONS: toc:nil

"This is a 'test'".
```

**Comment by tarleb** [comment]
Probably best to disable the "smart" extension which converts Unicode quotes: replacing `-t latex` with `-t latex-smart` should resolve this.

**Comment by peripatetikos** [comment]
Thanks, using latex-smart resolved the issue.
