### ISSUE TITLE
multiple bibliographies / indent behaviour

### ISSUE THREAD

**Issue by maehr** [pandoc/lua-filters#180]
Since Pandoc 2.14 there is a `\begin{CSLReferences}` wrapper / env around the bibliographies. Unfortunately the wrong parameters `{0}{0}` instead of `{0}{1}` or  `{1}{1}` are passed to it. Passing `indent=true` to Pandoc does not change this behaviour.

```tex
\hypertarget{quellen-1}{%
\section{Quellen}\label{quellen-1}}

\hypertarget{refs_sources}{}
\begin{CSLReferences}{0}{0}  % #1 hanging-ident, #2 entry spacing
\leavevmode\vadjust pre{\hypertarget{ref-maeder1965a}{}}%
Adank, This~(Reg.): Stop der Spontan-Einwanderung, Antenne, 7 m 40 s,
Schweizer Radio und Fernsehen, Bern 20.01.1965, SRF. Online:
\textless{}\url{https://www.srf.ch/play/tv/antenne/video/stop-der-spontan-einwanderung?id=44119ab7-4326-4e62-9ec0-3df2d78a7e45}\textgreater.
```

**Comment by badumont** [comment]
I noticed this with 2.13 too.

**Comment by maehr** [comment]
> I noticed this with 2.13 too. Le Wednesday 02 June 2021 à 02:12:45AM, Moritz Mähr a écrit :
> […](#)
> Since Pandoc 2.14 there is a \begin{CSLReferences} wrapper / env around the bibliographies. Unfortunately the wrong parameters {0}{0} instead of {1}{0} are passed to it. Passing Vindent=true to Pandoc does not change this behaviour. \hypertarget{quellen-1}{% \section{Quellen}\label{quellen-1}} \hypertarget{refs_sources}{} \begin{CSLReferences}{0}{0} \leavevmode\vadjust pre{\hypertarget{ref-maeder1965a}{}}% Adank, This~(Reg.): Stop der Spontan-Einwanderung, Antenne, 7 m 40 s, Schweizer Radio und Fernsehen, Bern 20.01.1965, SRF. Online: \textless{}\url{[https://www.srf.ch/play/tv/antenne/video/stop-der-spontan-einwanderung?id=44119ab7-4326-4e62-9ec0-3df2d78a7e45}\textgreater](https://www.srf.ch/play/tv/antenne/video/stop-der-spontan-einwanderung?id=44119ab7-4326-4e62-9ec0-3df2d78a7e45%7D%5Ctextgreater). — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.*

In my case with pandoc 2.13 it omitted the wrapper / env completely on a Mac 10.15.7.

```tex
\hypertarget{quellen-1}{%
\section{Quellen}\label{quellen-1}}

\hypertarget{refs_sources}{}
\leavevmode\vadjust pre{\hypertarget{ref-maeder1965a}{}}%
Adank, This~(Reg.): Stop der Spontan-Einwanderung, Antenne, 7 m 40 s,
Schweizer Radio und Fernsehen, Bern 20.01.1965, SRF. Online:
\textless{}\url{https://www.srf.ch/play/tv/antenne/video/stop-der-spontan-einwanderung?id=44119ab7-4326-4e62-9ec0-3df2d78a7e45}\textgreater.
```

**Comment by maehr** [comment]
I just found out that this issue is due to a certain CSL style <https://www.infoclio.ch/en/citation-style> and my inability to read its specs accurately.

If you want to change the environment I propose this quick fix:

```yaml
header-includes:
  - |
    ```{=latex}
    % quick fix to get an hangindent for the bibliographies
    \renewenvironment{CSLReferences}[2]
    {%
      \let\oldpar\par
      \def\par{\hangindent=\cslhangindent\oldpar}
      \setlength{\parskip}{1\cslentryspacingunit}
    }%
    {}
    ```
```
