### ISSUE TITLE
short-captions: Automatically truncate caption (after first sentence / given a regex)

### ISSUE THREAD

**Issue by phirsch** [pandoc/lua-filters#20]
I find that truncating the long caption after the first sentence often suffices for my needs, i.e. truncate the caption after the first period which is not followed by a space. A somewhat more general variant could also use a (lookahead?) regex given as a further attribute. I just tried to add this myself, but unfortunately, my knowledge of Lua and Pandoc AST internals is not yet up to the task...

**Comment by tarleb** [comment]
Apologies for the late reply, it seems that this issue got lost. I think this is out of scope for the short-captions filter, hence closing.
