### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by louisabraham** [pandoc/lua-filters#21]
What is the recommended method to install?

As I understand it, you have to put the complete path after `--lua-filter`.

(I tried to modify my `$PATH$`)

**Comment by jgm** [comment]
You can put lua filters in the filters subdirectory of your
user data directory (normally `~/.pandoc`).

@tarleb, putting lua-filters in the path doesn't work (it
works for regular filters).  Perhaps we should consider
either revising the documentation (which suggests that all
the methods that work for --filter work for --lua-filter)
or making it possible to find executable lua filters in the
path?

**Comment by jgm** [comment]
> I also tried to put `task-list.lua` (for example) in the ~/.pandoc folder, but got the same error.

Put in in `~/.pandoc/filters`.

> IMO, there should be a way to clone a repository like https://github.com/pandoc/lua-filters/ in ~/.pandoc (like with https://github.com/citation-style-language/styles that you can clone in ~/.csl).

I believe you can already do this.  Clone it as `filters`, though.
And you'll need to specify the path relative to `filters`, e.g.:

    --lua-filter wordcount/wordcount.lua

**Comment by louisabraham** [comment]
Thanks for your help.

I believe this should be specified somewhere in the doc, though.

**Comment by jgm** [comment]
louisabraham <notifications@github.com> writes:

> Thanks for your help.
>
> I believe this should be specified somewhere in the doc, though.

I've already added something under `--lua-filter`.

**Comment by tarleb** [comment]
@jgm would it make if we were to start making releases? Putting all filters in a single, flat archive would allow for straight-forward installation instructions. Do you think it would be worth the effort?

**Comment by jgm** [comment]
I'm not sure.  My thought was that generally people would want
just one or two fo these filters; if there's a release, then you
get the whole box (and it might get quite big).

Perhaps better would be a command-line tool that extracts
the filters you need to the right places?

**Comment by tarleb** [comment]
Makes sense. I'm not getting much open source work done these days, but I'll keep it in mind.

**Comment by jgm** [comment]
I wouldn't personally make it a priority.  Not too hard for
people to download the lua script themselves and put it where
it's needed.

**Comment by microraptor** [comment]
If people read this and simply want to install/update all lua files of the filters from Github flat into the filters home directory under linux:

```sh
mkdir -pv ~/.pandoc/filters
git clone --depth=1 'https://github.com/pandoc/lua-filters' '/tmp/pandoc-lua-filters-git'
mv -v /tmp/pandoc-lua-filters-git/**/*.lua ~/.pandoc/filters
rm -rf '/tmp/pandoc-lua-filters-git'
```

Replace `~/.pandoc/filters` with `~/.local/share/pandoc/filters`, if you prefer it.

**Comment by mfhepp** [comment]
> If people read this and simply want to install/update all lua files of the filters from Github flat into the filters home directory under linux:
> 
> ```shell
> mkdir -pv ~/.pandoc/filters
> git clone --depth=1 'https://github.com/pandoc/lua-filters' '/tmp/pandoc-lua-filters-git'
> mv -v /tmp/pandoc-lua-filters-git/**/*.lua ~/.pandoc/filters
> rm -rf '/tmp/pandoc-lua-filters-git'
> ```
> 
> Replace `~/.pandoc/filters` with `~/.local/share/pandoc/filters`, if you prefer it.

One thing: I think it will make sense to keep the clone of the Git repository, so not cloning into tmp/*** but a permanent place, at least if one is building a reproducible work environment.

Why? Because then you can check and fetch any improvements from the upstream repository, and if there are changes, copy the files to  `~/.pandoc/filters` .

If you delete the cloned repository, it is very difficult to check for improvements, and equally difficult to create pull requests for feeding back.

**Comment by tarleb** [comment]
That's @mfhepp. Should we add this as alternative install instructions to the README? PR welcome.
