### ISSUE TITLE
Thanks: list-table filter is awesome!

### ISSUE THREAD

**Issue by gabyx** [pandoc/lua-filters#225]
@not-my-profile and @tarleb:
Who ever invented and maintains this `list-table.lua` filter: **Thanks very much**. Its **really awesome**, and should really become another standard table in `pandoc`. Its probably the best table style to maintain and I can see only benfits when using it.

Output see here:
https://gabyx.github.io/TechnicalMarkdown/docs/html-package/Content.html#rst-style-table

**Comment by tarleb** [comment]
:heart:

Credit for the filter should go to @not-my-profile.
