### ISSUE TITLE
Is there a sandbox for draft filters?

### ISSUE THREAD

**Issue by fxpar** [pandoc/lua-filters#241]
Hi, 
I am working (very slowly) on two filters... 
How to "pre-push" them while they are unfinished, so that people who want to participate can, but without putting a stain on the whole project?
Thanks

**Comment by tarleb** [comment]
Thank you for asking. New filters should best go to a new repository and then be linked in the pandoc wiki and/or here. There is a template repo here that can be used: [lua-filter-template](https://github.com/tarleb/lua-filter-template). See the discussion in #207 for more info.

I've added a note to the README just now (and should have done so sooner).
