### ISSUE TITLE
Scholarly Metadata Lua - unexpected symbol

### ISSUE THREAD

**Issue by trickard1000** [pandoc/lua-filters#246]
Hello.

My apologies if this is not the right place to locate such a query. I am trying to run scholarly metadata lua along with author info blocks to render a PDF from MD with a YAML frontmatter. 

This was my input: 

- pandoc --lua-filter=scholarly-metadata.lua --lua-filter=author-info-blocks.lua  --citeproc --bibliography Library.yaml -s -o output.pdf template_test.md

This works without the filters to make a PDF. With the filters, I get:

- Error running filter scholarly-metadata.lua:
scholarly-metadata.lua:8: unexpected symbol near '<'

My YAML, in case of relevance (I am noob):

title: "Dam the River: Ontological exclusion in global and Brazilian Integrated Water Resource Management"
author: 
- name: Thomas Rickard 
   affiliation: Federal University of Minas Gerais 
   email: trickard1000@gmail.com
keywords: [Water, Governance, Ontology, Participation, Brazil]
date: August, 2022

My thanks for any pointers,
Thomas

**Comment by tarleb** [comment]
The most likely cause is that the HTML was stored in the `.lua` file. That can happen if one clicks `Save link` on the file in the GitHub repo. Try to replace the Lua files with these instead:
https://raw.githubusercontent.com/pandoc/lua-filters/master/scholarly-metadata/scholarly-metadata.lua
https://raw.githubusercontent.com/pandoc/lua-filters/master/author-info-blocks/author-info-blocks.lua
