### ISSUE TITLE
cito.lua fails on citations without a cito property

### ISSUE THREAD

**Issue by tolot27** [pandoc/lua-filters#25]
If cito.lua is applied, it throws the following error, if a citation does not have a cito property:

```
Error running filter cito.lua:
Could not read list: Could not get Inline value: Expected a string but got a nil
```

It should work anyway and should default to `citation` or `cites`.

**Comment by tarleb** [comment]
Fixed in aef0e63ba9605a922bfb279173f7481dee07ada6.
