### ISSUE TITLE
Filter for adding attributes to all elements?

### ISSUE THREAD

**Issue by mustafa0x** [pandoc/lua-filters#251]
There's a [10-year-old open feature request](https://github.com/jgm/pandoc/issues/684) for this, and djot adds support, but for us still using pandoc's markdown, is there a filter that adds such a feature? Especially for lists.

**Comment by jgm** [comment]
This is not something that could be added by a filter; the pandoc AST does not have slots for attributes on all elements.

However, you can emulate this using `commonmark_x` -- see https://pandoc.org/MANUAL.html#extension-attributes
