### ISSUE TITLE
Request: Support nested titles in docbook reader for orderedlist and itemized elements

### ISSUE THREAD

**Issue by aireilly** [pandoc/lua-filters#253]
When I try the following conversion, the <title/> element gets swallowed by the pandoc conversion. I don't see anything in the output.

$ cat docbook.xml
```
<orderedlist numeration="arabic">
    <title>Procedure</title>
    <listitem>
        <simpara>Create something new.</simpara>
    </listitem>
</orderedlist>
```

$ pandoc -f docbook docbook.xml -t markdown > out.md

$ cat out.md
`1.  Create something new.`

It would be good to render these elements fully.

Thanks!

**Comment by tarleb** [comment]
Sorry, I meant on the pandoc issue tracker (https://github.com/jgm/pandoc/issues). GitHub doesn't allow to transfer issues across different orgs, could you re-raise the issue there?

**Comment by aireilly** [comment]
https://github.com/jgm/pandoc/issues/8442
