### ISSUE TITLE
command line paramter for cito.lua to output or suppress simple citations

### ISSUE THREAD

**Issue by tolot27** [pandoc/lua-filters#26]
If #25 is fixed, it would be great to enable/disable the yaml output of simple citations with the property `citation` or `cites`.

**Comment by tarleb** [comment]
Removing those entries which are just marked as `citation` is possible by adding an extra filter

    function Meta (meta)
      meta.cito_cites.citation = nil
      return meta
    end

How would you like the switch to be used? I'm hesistant to add anything, as implementing and documenting a switch would add complexity. I'd rather keep the filter simple.
