### ISSUE TITLE
rationale for retiring this repo?

### ISSUE THREAD

**Issue by hholst80** [pandoc/lua-filters#274]
What is the rationale for retiring this repo? I found the great tool to have inline graphviz diagrams via this repo. I would never have found it without a central repository of useful tools.  I wanted to contribute back a D2 patch for it, but now, where would I submit it? Should I fork lua-filters? Should I make a standalone? How will we keep things organized?

Centralized package repos has proven itself to be best practice, so why move *away* from that? What other project has done this and it was a clear win for the community?

**Comment by alerque** [comment]
See #207. There will still be a central place in an org where repos are organized and probably an index of them as well, but the actual work maintaining the code is hard is a single repository. The new layout will help code owners and enable other interested parties to have permissions and keeep up with things in their wheel house.
