### ISSUE TITLE
mhchem Math function does not update AST

### ISSUE THREAD

**Issue by mcclurgm** [pandoc/lua-filters#276]
In the mhchem filter, Math elements are not updated. I think this is because the Math function does not return a value. See: https://github.com/pandoc/lua-filters/blob/2aa98bfda556c7d4dfb8e30c20b318b6fd1f5091/mhchem/mhchem.lua#L205-L207

I think that just returning `el` will solve this issue.

**Comment by jgm** [comment]
Thanks. Let me know if that doesn't fix it!
