### ISSUE TITLE
New release for pandoc-quotes.lua?

### ISSUE THREAD

**Issue by DominikVogel** [pandoc/lua-filters#277]
Hi there,

I was following the readme for pandoc-quotes.lua (https://github.com/pandoc/lua-filters/tree/master/pandoc-quotes.lua) but failed to get a working installation. The reason for that is that the readme instructs to download the latest release but the latest release (v.0.1.10) does not include the fix for #192. Downloading the latest version from the repository worked. 

You might want to release a new version of pandoc-quotes.lua or update the readme.

Thanks!

**Comment by jgm** [comment]
Note that the release link takes you to different repository. We don't have releases here. Perhaps you could put an issue on that repository.

**Comment by DominikVogel** [comment]
I see. However, isn't it a bit confusing that the readme in the pandoc/lua-filters repo redirects you to a different repo when the readme is about a file in the pandoc/lua-filters repo?

**Comment by DominikVogel** [comment]
I created a pull request to fix it
