### ISSUE TITLE
Garbled math characters in tikz images

### ISSUE THREAD

**Issue by Vftdan** [pandoc/lua-filters#280]
In `diagram-generator.lua`.

When `tikz` node labels contain math formulas, punctuation in them is rendered as incorrect characters.
Perhaps, it can be fixed by changing utf package configuration or avoiding pdf to svg conversion?

## Steps to reproduce

Create a markdown file with content:

````
``` tikz
\begin{tikzpicture}[]
	\node (mynode) at (10bp,10bp) [draw] {$\lbrace a, b \rbrace$};
\end{tikzpicture}
```
````

Compile it to pdf:

``` sh
pandoc -L diagram-generator.lua file.md -o file.pdf
```

## Result

![image](https://github.com/pandoc/lua-filters/assets/9785382/2f5dded3-ce77-4017-94ca-5b752ee3ca39)

**Comment by tarleb** [comment]
That filter moved to [pandoc-ext/diagram](https://github.com/pandoc-ext/diagram), the version here is unmaintained. We should probably remove it from this repo.

**Comment by jgm** [comment]
Or perhaps just add a prominent note in the README directing people to the better-maintained version?
