### ISSUE TITLE
"Merging" from luapandoc-filters

### ISSUE THREAD

**Issue by ickc** [pandoc/lua-filters#30]
There's some filters added in <https://github.com/pandoc-extras/luapandoc-filters> before this repo existed. Look at the dir. in <https://github.com/pandoc-extras/luapandoc-filters/tree/master/filters> and see if anything salvageable and after that pandoc-extras/luapandoc-filter should be gone for good.

**Comment by tarleb** [comment]
I added an improved version of the include.lua filter, so now we have merged everything except for `gabc.lua`. I don't know enough about that filter to include it here. @jperon, please let us know if you'd like to port your filter over to this repo.

**Comment by jperon** [comment]
@tarleb With pleasure ; just let me know, please, what would have to be done to have it merged.

**Comment by tarleb** [comment]
Great! All filters in this repo come with a README, plus some tests used to verify that the filters do what we expect. Best to take a look at other filters – the lilypond filter is somewhat similar in scope and might serve as an example.

The tests can assume that all dependencies have been installed. We are finalizing an Ubuntu Docker image, which should make it easier to install all required software. Just include a note in the README which TeX packages and other programs must be installed for the filter to work.

We are now exposing more helper functions, some of which you might find helpful: [pandoc.List:includes](https://pandoc.org/lua-filters#pandoc.list:includes), [pandoc.List:find_if](https://pandoc.org/lua-filters#pandoc.list:find_if), and the functions in module [pandoc.system](https://pandoc.org/lua-filters#module-pandoc.system).
