### ISSUE TITLE
Trouble getting started --- missing doco?

### ISSUE THREAD

**Issue by nrnrnr** [pandoc/lua-filters#31]
I'm having trouble getting started with Lua filters.  I have extensive
experience with Lua and with Haskell, but little experience with
Pandoc's data types and APIs.

Here are two points that illustrate my difficulty: 

  - The parameters to the functions listed in https://pandoc.org/lua-filters.html#inline
    (for example) don't seem to match the parameters to the functions that
    I write.  For example, the `Span` function is listed to take two
    parameters, "inline content" and "attributes", but as far as I can
    tell, both content and attributes are in the single parameter.
    
  - The `Span` function that I write has to look in a `.c` field, then
    pull things out of there.  I don't see where the existence of the
    `.c` field is documented.

I've managed to make some progress by looking carefully at the Haskell
API for Pandoc's main data types, and by reverse engineering the Lua
code with print statements.  I am not having much fun.

Where would I find the following?

  - Some sort of Rosetta stone that would tell me
    how the Haskell types are represented in Lua?

  - An API specification for the functions I write---not just the ones
    I can call?

(Apologies if this is the wrong place.  I have not found a good place to ask beginner's questions about pandoc.)

**Comment by jgm** [comment]
This is definitely a pain point in the documentation.
The function you're seeing in the documentation, pandoc.Span,
is a function that *generates* a Span element. The
Span function you write is a function that is applied
to Span notes in the AST when the filter walks through
it. So these are really completely different
functions, with different types.  The function
applied to Spans in walking the AST takes a single
argument.

We have decent documentation for the
element-generating functions, but we need better
documentation for writing the node-visiting functions.
(We do have quite a few examples, not just in the
docs but in the pandoc/lua-filters repository,
but that's not good enough.)

@tarleb, can this be improved?  (Or does anyone
else who knows the filter API well want to chip in?)

**Comment by tarleb** [comment]
Agreed, the docs still leave a lot to be desired. I find that it takes me a higher level of concentration to produce anything readable than it takes me to program. This makes it more difficult to squeeze it into a few minutes here and there, which is how I often get open source stuff done. Let's see if I can reserve longer periods of time exclusively for documentation.

There is an article on [lua.space](https://lua.space) (slightly [updated version](https://www.zeitkraut.com/posts/2017-12-23-extending-pandoc-with-lua.html)) about pandoc's use of Lua. I intended it as a high-level intro to Lua filters and AST manipulations. Maybe it's helpful.

**Comment by jgm** [comment]
What would be most helpful is just a list of the
accessors for the different features of each
element.  For example, with a header you can do

    .level
    .content
    .classes
    .attributes
    .id (or is it .identifier?)

Just a list like this would really help a lot.

Another thought:  it would be neat if you could get
an interactive environment to explore and debug
filters.  Something like 'pandoc --lua-repl'.
Then you could create a Header and inspect its
attributes, etc.

**Comment by nrnrnr** [comment]
One of the challenges here is that the accessors like `.content` and `.attr` are hidden in a metatable.  This is probably why I didn't discover them while probing from the Lua environment.  (First, I didn't think to interrogate the metatable, and second, even if I had, quite likely the key information is hidden inside a closure.)

As a first cut, perhaps the lua-filters documentation could be updated as follows?

  - Right away, note that the `Span` I write is not the same as the `pandoc.Span` that is called.  This idea is kind of implicit in the existing doco, but making it explicit would help.
  - Soon, to serve as a stopgap, a pointer to somewhere in the source code where Haskell values are embedded into Lua.
  - Eventually, documentation for each function in the filter API (that is, the functions I write when creating a filter), to include information about the "type" (loosely speaking) of each parameter.  
  - Eventually, an explanation of the accessors available for each Lua type (as suggested by @jgm above).

At some point I would love to see user-facing documentation of the mapping of Pandoc's Haskell types to Pandoc's Lua types, because that's how I roll, but the sketches above would help a lot.

(I should say in passing that I am absolutely thrilled to be able to write Pandoc filters in Lua.)

**Comment by tarleb** [comment]
I've added a [first draft](https://github.com/jgm/pandoc/blob/36a6a40ef7db36686630adf8ccb18a0fa252768f/doc/lua-filter-types-and-objects.md) to the docs folder.

Another stopgap is to use the module documentation in <https://pandoc.org/lua-filters.html#module-pandoc>. A rule of thumb is that if the constructor for an element takes a parameter of name `x`, then the created object will also have a field of name `x`.  However, there are a few exceptions (e.g. `Meta`).

Most marshaling work is done by code from the file [`data/pandoc.lua`](https://github.com/jgm/pandoc/blob/master/data/pandoc.lua). Pandoc calls these constructors when pushing values to the stack. The file is not a simple read as it contains large chunks of metaprogramming, and I'd write it differently today.

**Comment by jgm** [comment]
Albert Krewinkel <notifications@github.com> writes:

> I've added a [first draft](https://github.com/jgm/pandoc/blob/36a6a40ef7db36686630adf8ccb18a0fa252768f/doc/lua-filter-types-and-objects.md) to the docs folder.

This is a great start. Is the idea eventually to add
this to the main lua-filters document?

**Comment by tarleb** [comment]
I haven't thought about that yet. Adding it to the main doc seems like a good idea.

I'm taking a brief detour before finishing this up; maybe we can have a central file from which Lua *and* JSON documentation can be created, as it should be very similar. A YAML file with information similar to that in a JSON schema, plus additional descriptions, seems to be the most versatile/least verbose format for this. Does it seem like this could be worth the additional effort?

**Comment by tarleb** [comment]
The document should now be acceptable as a first iteration. I'll merge this into the main doc within the next couple of days.

**Comment by tarleb** [comment]
OK, merged the doc.

@nrnrnr, would you consider it helpful if we were to define a `__pairs` metamethod on all elements, such that it becomes simpler to iterate over the fields and their names?

**Comment by nrnrnr** [comment]
@tarleb my apologies for the delayed reply.  I think the primary value of a `__pairs` metamethod would be as machine-readable documentation.  By itself, it would be worth a little.  As part of a more systematic approach to documenting the Lua, it would be worth more.  But I wouldn't press for it.

**Comment by tarleb** [comment]
The docs are still far from perfect, but at least we now document all element attributes and cross-link element constructors to their types, thus closing. I have plans for a more self-documenting system, but this requires a lot of groundwork to be done first.
