### ISSUE TITLE
Minor issue: 'multiple-bibliographies' filter still throws one error per citation

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [pandoc/lua-filters#32]
Coming from the [discussion over at pandoc discuss](https://groups.google.com/forum/#!topic/pandoc-discuss/dT6eRRlrxJg), I'd like to record that erroneous notifications such as
`pandoc-citeproc: reference XY not found`
have been reduced by the uploaded `multiple-bibliographies` filter, but not yet eradicated completely: There's still _one_ error per citation.

While this is a minor issue - after all the functionality is not affected -, in a document with hundreds of citations, this may still lead to oneself missing _warranted_ error notifications in case a cited work is really not included in the bibliography.

Don't want to be pedantic, but I thought noting the issue here couldn't hurt. Again, thanks for uploading the filter in the first place!

**Comment by tarleb** [comment]
Thanks for the reminder. Warnings should disappear now if the pandoc-citeproc version is 0.14.5 or later.
