### ISSUE TITLE
Any way to run a list of blocks through a filter?

### ISSUE THREAD

**Issue by a-vrma** [pandoc/lua-filters#33]
I'm trying to write a file transclusion filter for markdown documents and I ended up with [one that works
pretty well](https://github.com/a-vrma/pandoc-filters/blob/5a0cabbc6512a96b7677e589433072649e2fb3dc/transclude.lua).

But, I have no idea how to make it work recursively.
I tried mapping a function to the `pandoc.List` object, but that doesn't work because the function returns a list of blocks inside a block.
I thought of using `walk_block` but that only works inside blocks.
I know that one can just use the m4 preprocessor for this task (and that is what I'm currently using)
but I wanted to make a fully portable filter just for fun.

Is there any way of doing this?

**Comment by jgm** [comment]
Please ask this on the pandoc-discuss mailing list;
that's the best place to get help on filters.

**Comment by a-vrma** [comment]
@tarleb 
That worked perfectly and fixed my issue. Thanks.
