### ISSUE TITLE
replace_todo_markers fails with nil input

### ISSUE THREAD

**Issue by markgweber** [pandoc/lua-filters#35]
I am using Atom with Pandoc for Markdown Preivew Plus.  I'm using the `--lua-filter=task-list.lua` option to convert my task lists.  When I type a * or - at the beginning of a line (empty list item)  I immediately get the following error.

Command failed: /usr/local/bin/pandoc --from=markdown-raw_tex+tex_math_single_backslash --to=html --lua-filter=task-list.lua Error running filter task-list.lua: Error while running filter function: /Users/xxxxxx/.pandoc/filters/task-list.lua:90: attempt to index a nil value (local 'blk')

If I continue to type, it begins to correctly render again however it leaves the error overlay in the editor. 

I have a functional workaround by inserting a quick check at the top of the function to return if blk is nil.  Although this works for my purposes, I am not a lua programmer and I have no earthly idea what other ramifications this might have.

```lua
function M.replace_todo_markers (blk, format)
+  if blk == nil then
+    return
+  end
```

**Comment by tarleb** [comment]
Thanks for the report. Your fix is spot-on, though I'd merge it with the next line:

    if blk == nil or blk.t ~= 'Para' and blk.t ~= 'Plain' then
      return nil
    end

I fixed it but will have to push it later, as the network I'm on blocks all SSH traffic.
