### ISSUE TITLE
fd:4: hClose: resource vanished (Broken pipe)

### ISSUE THREAD

**Issue by jartigag** [pandoc/lua-filters#4]
I'm running
`pandoc file.md --filter ./task-list.lua -o file.pdf`
to test task lists in GitHub-flavored Markdown, but i get
`pandoc: Error running filter ./task-list.lua
fd:4: hClose: resource vanished (Broken pipe)`

What's wrong?

**Comment by tarleb** [comment]
Please use `--lua-filter` instead of `--filter`. Note that the filter works best with the latest pandoc 2.0.6.

**Comment by jartigag** [comment]
It creates the pdf file with
`pandoc file.md --pdf-engine=xelatex --lua-filter ./task-list.lua -o file.pdf`
(`texlive-xetex`, `texlive-luatex` and `texlive-math-extra` apt packages needed), but..
```
[WARNING] Missing character: There is no ☐ in font [lmroman10-regular]:mapping=tex-text!
[WARNING] Missing character: There is no ☑ in font [lmroman10-regular]:mapping=tex-text!
```
How do I fix it?

**Comment by tarleb** [comment]
I've updated the filter to use create the ballot box by combining square and checkmark. Can you test again?

**Comment by jartigag** [comment]
It works perfectly :ok_hand: Thanks!
