### ISSUE TITLE
Make tests more resistent against changes in pandoc

### ISSUE THREAD

**Issue by tarleb** [pandoc/lua-filters#46]
Many tests use golden files to check correctness of the produced output. This is fragile and breaks whenever the pandoc template changes for the given format. Tests should rather check for the existence of certain keywords in the output.

Filters with fragile tests:

- [x] scrlttr2
- [x] track-changes
- [x] table-short-captions

**Comment by blake-riley** [comment]
I've updated the testing for table-short-captions.
Thanks for the examples in the other two filters.
