### ISSUE TITLE
scrlltr2 comparison to template

### ISSUE THREAD

**Issue by Konfekt** [pandoc/lua-filters#55]
For someone new to pandoc, could someone explain the advantages of using a lua-filter instead of a template for scrlttr2 such as https://github.com/JensErat/pandoc-scrlttr2 ?

**Comment by tarleb** [comment]
For me, as maintainer and user, the advantage is that I don't have to worry about the template being out of date. Pandoc's LaTeX template is quite sophisticated, has many bells and whistles, and ensures that even problematic constructs (like verbatim text in a table footnote) work as expected. Any relevant changes to this template should be merged into a custom template to get the best results.

Another advantage is that it's easier to add some convenience with a filter, like the option to adjust the date-format.

All this is less important for letters, which are usually rather simple documents. It's still nice to know that all improvements to pandoc are immediately available when using a filter, without the need to check and update a template.

**Comment by Konfekt** [comment]
Thank you, makes perfect sense.
