### ISSUE TITLE
Put individual filter tests in $FILTER/tests subdirs?

### ISSUE THREAD

**Issue by jkr** [pandoc/lua-filters#7]
When I open up a filter folder, it takes a bit for my eye to find the filter itself. I think it might be off-putting for users pointed from pandoc-discuss or elsewhere.

What about

~~~
|-- bibexport
|    |-- README.md
|    |-- bibexport.lua
|    +-- tests
|         |-- Makefile
|         |-- coffee.bib
|         |-- expected.bibexport.aux
|         +-- ...
|
|-- section-refs
|    |-- README.md
|    |-- section-refs.lua
|    +-- tests
|         |-- Makefile
|         |-- bibliography.bib
|         +-- ...
...
~~~

and then just change `FILTERS` in the top Makefile to point accordingly?

**Comment by jgm** [comment]
Yes, maybe this is a good idea. On the other hand, the
sample.md files one sees are sometimes helpful as documentation.
Anyone else have thoughts on this?

+++ Jesse Rosenthal [Jan 11 18 07:43 ]:

**Comment by tarleb** [comment]
Fine with me. Alternatively, we could prefix files not intended to be inspected by users with `test-`, but a subdir approach seems cleaner.

**Comment by frederik-elwert** [comment]
> Yes, maybe this is a good idea. On the other hand, the sample.md files one sees are sometimes helpful as documentation. Anyone else have thoughts on this?

Could the sample.md remain in the main folder, and the test would just reference it? E.g.,

```Makefile
test:
	@pandoc --lua-filter=myfilter.lua --output=output.md ../sample.md
	@$(DIFF) expected.md output.md
	@rm -f output.md
```
