### ISSUE TITLE
fromlogo field does not take image file in scrlttr2.lua

### ISSUE THREAD

**Issue by jooyoungseo** [pandoc/lua-filters#78]
I was attempting to put my logo (png file) in my cover letter using `scrlttr2.lua` filter.
According to the instruction, it seems like I can pass my logo image file_name to either `fromlogo` or `logo` field in YAML.
However, it does not put my image for my letter; instead, it prints the file name string of the logo image in the pdf output.

Would you mind taking a look at this issue?

Many thanks.

**Comment by tarleb** [comment]
Apologies for the delayed response. Could you describe in more detail how you are using the `logo` field?

We currently expect that not only the filename, but a real image object is specified. E.g.

``` yaml
---
logo: '![company logo](path/to/logo.png)'
---
```

But we could think about converting strings to images if the string looks like an image filename.

**Comment by jooyoungseo** [comment]
Thank you very much, @tarleb! Now it works. I did not enclose the image object with quotation mark. Previously, I tried with  ...

```yaml
logo: "logo.png"
```

and,

```yaml
logo: ![Logo](path/to/logo.png)
```

I had to escape the image object in YAML.

BTW, the alt text provided for logo image does not work. FYI, I am a screen reader user; however, the pdf output does not include the logo image alt text that I provided inside `![]`.

Would there be any way to fix this issue?

Many thanks.

**Comment by tarleb** [comment]
I coded an auto-detection mechanism, but decided that it adds to much complexity for what it achieves. It is probably better to improve the docs instead. Would it have prevented confusion if the docs said "`fromlogo` (alias: `logo`): item to be used as the sender's logo?"

The missing alt text is a pandoc issue, see jgm/pandoc#5409.
