### ISSUE TITLE
bibexport does not handle well BibLaTeX entries

### ISSUE THREAD

**Issue by jooyoungseo** [pandoc/lua-filters#86]
Currently it does not seem like `bibexport` simply finds and exports cited bib entries.

For example, `@online` is one of the entries that bibexport does not export in an appropriate form.

My guess is that `bibexport` just only does a good job for `BibTeX` entries, not for other newly added types in `BibLaTeX`.

Would there be any way to simply parse multiple bib file entries and export them into one bib file regardless of their entry types?

`bibexport` does not feel universal.

**Comment by tarleb** [comment]
Sorry for the late response, this somehow got lost.

Unfortunately, I'm not aware of a similar tool for BibLaTeX.

**Comment by tarleb** [comment]
Closing this now, but if anyone finds this issue and knows how to do this, I'd consider including it in the filter.
