### ISSUE TITLE
Feature request: add mermaid to lua-filters/diagram-generator

### ISSUE THREAD

**Issue by David-Else** [pandoc/lua-filters#93]
https://mermaid-js.github.io/mermaid/#/

There is a cli app https://github.com/mermaid-js/mermaid-cli available. You just need to npm install `@mermaid-js/mermaid-cli` and run it using `npx`. As an example, to process all the files once extracted:
```shell
for i in *.mmd; do npx mmdc -i "$i" -o "${i%.*}.png" -b transparent -t forest; done
```
Would be great to get that included!

**Comment by tarleb** [comment]
The diagram generator is now maintained at https://github.com/pandoc-ext/diagram. Mermaid support has been added there.
