### ISSUE TITLE
abstract-to-meta filter corrupts lists

### ISSUE THREAD

**Issue by rriemann-eu** [pandoc/lua-filters#94]
Dear all,

Thank you very much for the filter collection. They can simplify our input files. I noticed though that the filter `abstract-to-meta` does not copy over lists.

Best,   
Robert

## Minimal example

Command for testing: `pandoc --atx-header -L abstract-to-meta.lua -s -t markdown input.md > output.md`

### input.md

~~~markdown
# Abstract

Abstract text.

- one
- two

# Next Section

Other text.
~~~

### output.md

~~~markdown
---
abstract: |
  Abstract text.

  one

  two

  -   
  -   
---

# Next Section

Other text.
~~~

**Comment by jgm** [comment]
@tarleb

**Comment by tarleb** [comment]
Thanks for the report.

**Comment by tarleb** [comment]
Just fyi: I believe that this problem was introduced with the release of pandoc 2.8, which features a new element traversal order. The previous code relied on the old traversal order.
