### ISSUE TITLE
[abstract-to-meta] Abstract created even when no such header

### ISSUE THREAD

**Issue by jpcirrus** [pandoc/lua-filters#97]
The change in 8fc5add broke the previous behaviour where the filter could also be run on a document which did not have an Abstract header without effect. What happens now in that case is that an Abstract is created with the contents of `true`.

The use case is having a pandoc defaults file for report/article type documents with the `filters` key as follows:

```yaml
filters:
  - abstract-to-meta.lua
  - pandoc-crossref
  - pandoc-citeproc
```

This enables a generic build system to be able to compile various report/article documents, some of which require an abstract and others that don't. This change prevents that from being possible.

**Comment by tarleb** [comment]
Thanks for the report!
